import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";
import { v4 as uuid } from 'uuid';
import { ApiProperty } from '@nestjs/swagger';

@Entity({ name: 'roles' })
export class Role{

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;
    
    @ApiProperty({
        example: 'admin',
        description: '"nombre"',
        nullable: false,
        type: String,
    })
    @Column('text',{
        nullable:false,
        unique:true
    })
    nombre: string;

    @ApiProperty({
        example: true,
        description: '"estado"',
        default: true,
        type: Boolean
    })
    @Column('bool', {
        default: true
    }) 
    estado: boolean;
     
}
