import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Producto } from './producto.entity';
import { ApiProperty } from '@nestjs/swagger';
import { v4 as uuid } from 'uuid';

@Entity({ name: 'producto_images' })
export class ProductoImage {

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;


    @Column('text')
    @ApiProperty({
        example: "https://loremflickr.com/640/480/abstract?lock=20438",
        description: '"url"',
        type:String

    })
    @Column('text')
    url: string;

    @ManyToOne(
        () => Producto,
        ( producto ) => producto.images,
        {  onDelete: 'CASCADE' }
    )
    producto: Producto


    @ApiProperty({
        example: false,
        description: '"external"',
        default: false,
        type: Boolean,
    })
    @Column('bool',{
        default: false
    })
    external : boolean;

}