import { Categoria } from "src/categorias/entities/categoria.entity";
import { DetallePedido } from "src/detalle-pedido/entities/detalle-pedido.entity";
import { BeforeInsert, BeforeUpdate, Column, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { ProductoImage } from "./producto-image.entity";
import { ApiProperty } from '@nestjs/swagger';
import { v4 as uuid } from 'uuid';

@Entity({ name: 'productos' })
export class Producto {
    

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;


    @ApiProperty({
        example: 'gaseosa',
        description: '"nombre"',
        nullable: false,
        type: String,
    })
    @Column('text', {
        nullable: false,
        unique: true 
    })
    nombre: string;

    @ApiProperty({
        example: '3L inca Kola',
        description: '"descripcion"',
        nullable: false,
        type: String,
    })
    @Column('text', {
        nullable: false,
    })
    descripcion: string;

    @ApiProperty({
        example: 12.50,
        description: '"precio"',
        nullable:false,
        type: Number

    })
    @Column('decimal',{
        precision: 9, scale: 2,
        nullable:false
    })
    precio: number;


    @ApiProperty({
        example: 3,
        description: '"cantidad"',
        nullable:false,
        type: Number

    })
    @Column('int', {
        default: 1,
        nullable:false
    })
    cantidad: number;

    @ApiProperty({
        example: { id: uuid() },
        description: '"categoria"',
        type: () => Categoria,
        nullable: false
    })
    @ManyToOne(
        () => Categoria,
        ( categoria ) => categoria.producto,
        { eager: true , nullable:false}
    )
    categoria: Categoria

    @OneToMany(
        () => DetallePedido,
        ( detalle_pedido ) => detalle_pedido.producto
    )
    detalle_pedido: DetallePedido;


    @ApiProperty({
        example: true,
        description: '"estado"',
        default: true,
        type: Boolean
    })
    @Column('bool', {
        default: true
    })
    estado: boolean;


    @BeforeInsert()
    checkSlugInsert() {
        this.nombre = this.nombre.toLowerCase();
        if(!this.descripcion) this.descripcion = this.nombre.toLowerCase();
    }

    @BeforeUpdate()
    checkSlugUpdate() {
        if (this.nombre) this.nombre.toLowerCase();
    }

    @ApiProperty({
        example: [{
            id: '15af05aa-62d4-4b2f-ba54-3e1cb66ff5d6',
            url: '"https://loremflickr.com/640/480/abstract?lock=82631"'
        }],
        description: '"images"',
        nullable: false,
        type: () => ProductoImage,
    })
    @OneToMany(
        () => ProductoImage,
        (producto_images) => producto_images.producto,
        { cascade: true, eager: true }
    )
    images?: ProductoImage[];
    
}
