import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Categoria } from './categoria.entity';
import { ApiProperty } from '@nestjs/swagger';
import { v4 as uuid } from 'uuid';


@Entity({ name: 'categoria_images' })
export class CategoriaImage {

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type:String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column('text')
    @ApiProperty({
        example: "https://loremflickr.com/640/480/abstract?lock=20438",
        description: '"url"',
        type:String

    })
    url: string

    @ManyToOne(
        () => Categoria,
        ( categoria ) => categoria.images,
        {  onDelete: 'CASCADE' }
    )
    categoria: Categoria

    @Column('bool',{
        default: false
    })
    @ApiProperty({
        example: false,
        description: '"external"',
        default: false,
        type: Boolean,
    })
    external : boolean;

}