import { ApiProperty, ApiTags } from "@nestjs/swagger";
import { BeforeInsert, BeforeUpdate, Column, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { v4 as uuid } from 'uuid';

@Entity({ name: 'empleados' })
export class Employee{


    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @ApiProperty({
        example: 'jesus',
        description: 'Employee nombre',
        nullable: false,
        type: String,
        minLength: 1
    })
    @Column('text',{
        nullable:false
    })
    nombre:string;

    @ApiProperty({
        example: '963852741',
        description: 'Employee telefono',
        nullable: false,
        type: String,
        minLength: 9,
        maxLength: 9
    })
    @Column('text', {
        nullable: false,
        unique:true
    })
    telefono: string;

    @ApiProperty({
        example: '78945612',
        description: 'Employee dni',
        nullable: false,
        type: String,
        minLength: 8,
        maxLength: 8
    })
    @Column('text', {
        nullable: false,
        unique:true
    })
    dni: string;

    @ApiProperty({
        example: true,
        description: 'Employee estado',
        type: Boolean,
        default: true
    })
    @Column('bool', {
        default: true
    })
    estado: boolean;
    

}
