import { CabeceraPedido } from "src/cabecera-pedido/entities/cabecera-pedido.entity";
import { BeforeInsert, BeforeUpdate, Column, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { ApiProperty } from '@nestjs/swagger';
import { v4 as uuid } from 'uuid';


@Entity({ name: 'comprobantes' })
export class Comprobante {

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String

    })
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @ApiProperty({
        example: "boleta",
        description: '"tipo"',
        default: "boleta",
        type: String

    })
    @Column('text', {
        nullable: false,
        default: 'boleta'
    })
    tipo: string;

    @ApiProperty({
        example: "10053548605",
        description: '"nro"',
        nullable:false,
        type: String

    })
    @Column('text', {
        unique: true,
        nullable: false
    })
    nro: string;

    
    @ApiProperty({
        example: { id: uuid() },
        description: '"cabeceraPedido"',
        type: () => CabeceraPedido,
        nullable: false
    })
    @ManyToOne(
        () => CabeceraPedido,
        (cabeceraPedido) => cabeceraPedido.comprobante,
        { eager: true, nullable: false, onDelete: 'CASCADE' }
    )
    cabeceraPedido: CabeceraPedido;


    @ApiProperty({
        example: true,
        description: '"estado"',
        default: true,
    })
    @Column('bool', {
        default: true
    })
    estado: boolean;

    @BeforeInsert()
    checkSlugInsert() {
        this.tipo = this.tipo.toLowerCase();
    }

    @BeforeUpdate()
    checkSlugUpdate() {
        if (this.tipo) this.tipo.toLowerCase();
    }

}