import { CabeceraPedido } from "src/cabecera-pedido/entities/cabecera-pedido.entity";
import { BeforeInsert, BeforeUpdate, Column, Entity, OneToMany, PrimaryGeneratedColumn } from "typeorm";
import { v4 as uuid } from 'uuid';
import { ApiProperty } from "@nestjs/swagger";



@Entity({ name: 'mesas' })
export class Mesa {

    @ApiProperty({
        example: "96856f1e-94f5-463b-acfa-e7f17db5770e",
        description: ' id "(autogenerated)"',
        default: uuid(),
        type: String
    })
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column('text', {
        nullable: false,
        unique: true
    })
    @ApiProperty({
        example: 'mesa_new',
        description: '"nombre"',
        nullable: false,
        type: String,
    })
    nombre: string;

    @ApiProperty({
        example: true,
        description: '"estado"',
        default: true,
        type: Boolean,
    })
    @Column('bool', {
        default: true
    })
    estado: boolean;

    @OneToMany(
        () => CabeceraPedido,
        ( cabecera_pedido ) => cabecera_pedido.mesa
    )
    cabecera_pedido: CabeceraPedido;
    
    @BeforeInsert()
    checkSlugInsert() {
        this.nombre = this.nombre.toLowerCase();
    }

    @BeforeUpdate()
    checkSlugUpdate() {
        if (this.nombre) this.nombre.toLowerCase();
    }
}

